openapi: "3.0.3"
info:
  title: Connexion Intro
  version: 1.0.0
servers:
  - url: http://0.0.0.0:8080/api/v1.0
paths:

  /health-check:
    get:
      x-openapi-router-controller: src.api.v1.views
      operationId: health_check
      summary: Health check

      responses:
        "200":
          description: The service returns this response when it is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

  /create-post:
    post:
      summary: Create a single Post
      requestBody:
        description: POST data to create a Post
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - content
                - category
              properties:
                title:
                  type: string
                  maxLength: 120
                content:
                  type: string
                author:
                  type: string
                  nullable: true
                category:
                  type: string
                  nullable: true
                  enum: [
                    "MUSIC",
                    "IT",
                    "POLITICS",
                  ]
      responses:
        "201":
          description: A Post was created successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - title
                  - content
                  - author
                  - category
                properties:
                  title:
                    type: string
                    maxLength: 120
                  content:
                    type: string
                  author:
                    type: string
                    nullable: true
                  category:
                    type: string
                    nullable: true
                    enum: [
                      "MUSIC",
                      "IT",
                      "POLITICS",
                    ]
        "400":
          description: The service could not understand the request
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                  status:
                    type: integer
                  title:
                    type: string
                  type:
                    type: string
